import '../scss/style.scss'
import '../scss/main.scss'
import '../scss/reset.scss'
import '../scss/header.scss'
import '../scss/menu-modal.scss'
import '../scss/mobile-menu.scss'
import '../scss/swiper-brands.scss'
import '../scss/swiper-price.scss'
import '../scss/swiper-technika.scss'
import '../scss/footer.scss'
import '../scss/fonts.scss'
import '../scss/fonts.scss'
///JS IMPORT

import '../js/swiper.js'
import '../js/modalBtn.js'
